# Generated by Django 3.1.7 on 2023-02-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUp',
        ),
    ]
